#!/bin/bash
#PBS -P w85
#PBS -q normal
#PBS -l walltime=8:00:00
#PBS -lmem=8GB
#PBS -lncpus=1
#PBS -l wd

# Source key R modules -- not that you will need the right packages installed
# as well (see comments in the script that is sourced)
# NOTE THIS IS ONLY FOR NCI, COMMENT OUT OTHERWISE
source R_modules.sh

Rscript merge_additional_stochastic_tsunami_into_netcdf.R --stochastic_slip
Rscript merge_additional_stochastic_tsunami_into_netcdf.R --variable_uniform_slip
