#!/bin/bash
#PBS -P w85
#PBS -q normalsr
#PBS -l walltime=5:00:00
#PBS -lmem=500GB
#PBS -lncpus=104
#PBS -ljobfs=50GB
#PBS -l wd
#PBS -l storage=scratch/w85+gdata/w85

source ../../../modules_R_431.sh

echo 'The sapphirerapids nodes have 104 cores: Ensure application_specific_metadata.R has DEFAULT_MC_CORES=104'

# Array with SWALS output directory, underneath ../../../swals/OUTPUTS, where we check rasters from
all_runnames=(\
"../../../swals/OUTPUTS/ptha/sea_level_vary/random_alaskaaleutians/" \
"../../../swals/OUTPUTS/ptha/sea_level_vary/random_kermadectonga2/" \
"../../../swals/OUTPUTS/ptha/sea_level_vary/random_kurilsjapan/" \
"../../../swals/OUTPUTS/ptha/sea_level_vary/random_newhebrides2/" \
"../../../swals/OUTPUTS/ptha/sea_level_vary/random_outerrisenewhebrides/" \
"../../../swals/OUTPUTS/ptha/sea_level_vary/random_outerrisesolomon/" \
"../../../swals/OUTPUTS/ptha/sea_level_vary/random_solomon2/" \
"../../../swals/OUTPUTS/ptha/sea_level_vary/random_southamerica/" \
)

first_run=${all_runnames[0]}

# Find the raster outputs from one run (we assume all model runs have the same number of domains).
testfile=$(ls $first_run'ptha18_random_scenarios'_*/raster*.tar | head -n1)
# Count the rasters in the multidomain outputs
maxrasts=$(tar --list -f $testfile | grep "max_stage_" | wc -w)

# Do the calculations for each source
for runname in ${all_runnames[@]}; do
  echo 'RUNNAME:' $runname $maxrasts;
  Rscript compute_exceedance_rates_at_logic_tree_mean.R $runname $maxrasts max_stage 0.001 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0;
done
