module load gdal

dir=sea_level_vary/highres_depth_with_variance/sea_level_vary-depth-LogicTreeMean-sum_of_source_zones

gdalbuildvrt -resolution highest $dir/exceedance_rate_with_threshold_0.001.vrt $dir/summed_HS_domain*depth_as_max_stage_minus_elevation0_domain__exceedance_rate_with_threshold_0.001.tif
gdalbuildvrt -resolution highest $dir/variance_of__exceedance_rate_with_threshold_0.001.vrt $dir/summed_HS_domain*depth_as_max_stage_minus_elevation0_domain__variance_of__exceedance_rate_with_threshold_0.001.tif
gdalbuildvrt -resolution highest $dir/Monte_Carlo_Upper_CI__exceedance_rate_with_threshold_0.001.vrt $dir/summed_HS_domain*depth_as_max_stage_minus_elevation0_domain__Monte_Carlo_Upper_CI__exceedance_rate_with_threshold_0.001.tif
