#!/bin/bash
#PBS -P w85
#PBS -q normalsr
#PBS -l walltime=04:00:00
#PBS -lmem=1000GB
#PBS -lncpus=208
#PBS -l wd
#PBS -l storage=scratch/w85+gdata/w85
#PBS -o run/log/Sumatra2004_time_varying_low_res.o
#PBS -e run/log/Sumatra2004_time_varying_low_res.e

source SWALS_ifort_modules_2023_B.sh

# Run with sea level = 0.0 m
mpirun -n 16 -map-by numa:SPAN -bind-to numa -x OMP_NUM_THREADS=13 -x OMP_PROC_BIND=TRUE \
    ./model_sapphirerapids \
    FujiSatake2007_time_varying_forcing_realistic.csv \
    multidomain_design_control_NNL4_lowres.nml \
    Sumatra2004_FujiiSatake2007_timevarying_lowres \
    full \
    0.0 > run/log/Sumatra2004_time_varying_low_res.log
