# Run the probabilistic inundation calculations
Rscript make_depth_epistemic_uncertainty_rasters.R ptha18_tonga_MSL0_meshrefine4_msl80cm 3 0.84
Rscript make_depth_epistemic_uncertainty_rasters.R ptha18_tonga_MSL0_meshrefine4_msl80cm 4 0.84
Rscript make_depth_epistemic_uncertainty_rasters.R ptha18_tonga_MSL0_meshrefine4_msl80cm 5 0.84
Rscript make_depth_epistemic_uncertainty_rasters.R ptha18_tonga_MSL0_meshrefine4_msl80cm 6 0.84
Rscript make_depth_epistemic_uncertainty_rasters.R ptha18_tonga_MSL0_meshrefine4_msl80cm 7 0.84

Rscript make_depth_epistemic_uncertainty_rasters.R ptha18_tonga_MSL0_meshrefine4_msl80cm 3 0.16
Rscript make_depth_epistemic_uncertainty_rasters.R ptha18_tonga_MSL0_meshrefine4_msl80cm 4 0.16
Rscript make_depth_epistemic_uncertainty_rasters.R ptha18_tonga_MSL0_meshrefine4_msl80cm 5 0.16
Rscript make_depth_epistemic_uncertainty_rasters.R ptha18_tonga_MSL0_meshrefine4_msl80cm 6 0.16
Rscript make_depth_epistemic_uncertainty_rasters.R ptha18_tonga_MSL0_meshrefine4_msl80cm 7 0.16

