#!/bin/bash
#PBS -P w85
#PBS -q normalsr
#PBS -l walltime=12:00:00
#PBS -lmem=500GB
#PBS -lncpus=104
#PBS -l wd
#PBS -l storage=scratch/w85+gdata/w85

path_swals=.
source ../../modules_SWALS_ifx_2024.sh

# Initial stage for Chile2010
stage_file=$path_swals/../sources/like_historic/Chile2010/FujiSatake2013//Fuji_chile2010_sources_SUM_KAJIURA_SMOOTHED.tif
# Default res and load balance. No tidal correction
multidomain_design_namelists=$path_swals/multidomain_design_control/NNL4_defaultRes_singleTide.nml
# Model name
model_name=chile2010_fuji
# Ambient sea level of 0.0m AHD, approximation of expected sea level
ambient_sea_level=0

# Run the model
mpiexec -n 8 -map-by numa:SPAN -bind-to numa -x OMP_NUM_THREADS=13 -x OMP_PROC_BIND=TRUE \
    $path_swals/model_build \
    $stage_file \
    $multidomain_design_namelists \
    $model_name \
    full \
    $ambient_sea_level > $path_swals/validation/log/$model_name.log$PBS_JOBID
