#
# Make a clean directory structure for the tifs generated by 
#    run_compute_exceedance_rates_for_threshold_depth_logic_tree_mean_newParallelPartition.sh
# AND 
#    all the *.sh scripts generated by `make_exceedance_rate_jobs.R` (epistemic uncertainty calcs over multiple nodes)
#

# This should match the beginning of the folders that will be moved to better locations
outdirname='ptha18-NSW2023-MIS-sealevel110cm'

for variable in depth max_stage; do
  # Move logic-tree-mean hazard & variance rasters to a clean location
  mkdir -p ${outdirname}/highres_${variable}_with_variance ;
  #mv ${outdirname}-${variable}-LogicTreeMean* ${outdirname}/highres_${variable}_with_variance;
  
  # Move epistemic uncertainty rasters to a clean location
  # 16th percentile
  mkdir -p ${outdirname}/highres_${variable}_epistemic_uncertainty/16pc; 
  mv *-${variable}_exrate_*_0.16_* ${outdirname}/highres_${variable}_epistemic_uncertainty/16pc/;
  # 84th percentile
  mkdir -p ${outdirname}/highres_${variable}_epistemic_uncertainty/84pc;
  mv *-${variable}_exrate_*_0.84_* ${outdirname}/highres_${variable}_epistemic_uncertainty/84pc/;
done
