#!/bin/bash
#PBS -P w85
#PBS -q normalsr
#PBS -l walltime=00:20:00
#PBS -lmem=1000GB
#PBS -lncpus=208
#PBS -l wd
#PBS -l storage=scratch/w85+gdata/w85
#PBS -e run/log/test_model_sappirerapids.e
#PBS -o run/log/test_model_sappirerapids.o

path_swals=.
source $path_swals/SWALS_ifort_modules_2023_B.sh

# Run with sea level = 0.6 m
mpirun -n 16 -map-by numa:SPAN -bind-to numa -x OMP_NUM_THREADS=13 -x OMP_PROC_BIND=TRUE \
    $path_swals/model_sapphirerapids \
    $path_swals/../sources/like_historic/FujiSatake2007/Fuji_andaman2004_unit_sources_SUM_KAJIURA_SMOOTHED.tif \
    $path_swals/multidomain_design_control_NNL4_defaultres_defaultloadbalance.nml \
    short_test_run \
    test \
    0.6 > $path_swals/run/log/test_model_sappirerapids.log
