#!/bin/bash
#PBS -P w85
#PBS -q normalsr
#PBS -l walltime=00:20:00
#PBS -lmem=500GB
#PBS -lncpus=104
#PBS -l wd
#PBS -l storage=scratch/w85+gdata/w85
#PBS -o ./test/log/model_load_balanced_singleTide.o
#PBS -e ./test/log/model_load_balanced_singleTide.e

path_swals=.
source $path_swals/../modules_SWALS_ifx_2024.sh

# Initial stage from Tohoku2011
stage_file=$path_swals/../sources/like_historic/Tohoku2011/YamazakiEtAl2018/yamazaki18_Tohoku11_sources_SUM_KAJIURA_SMOOTHED.tif
# Default res and load balance
multidomain_design_namelists=$path_swals/multidomain_design_control/NNL4_defaultRes_singleTide.nml
# Model name
model_name=model_load_balanced_singleTide
# Ambient sea level for HAT is 0.0 with tidal adjustment
ambient_sea_level=2.145

# Run the model
mpiexec -n 8 -map-by numa:SPAN -bind-to numa -x OMP_NUM_THREADS=13 -x OMP_PROC_BIND=TRUE \
    $path_swals/model_build \
    $stage_file \
    $multidomain_design_namelists \
    $model_name \
    test_load_balance \
    $ambient_sea_level > $path_swals/test/log/$model_name.log$PBS_JOBID 
