#
# Copy the gauge RDS files (generated by the scripts in ./plots/) to a directory
# ../analysis/gauge_RDS_files/
# Then we do analysis in ../analysis/, and avoid cluttering this directory
#

output_basedir = '../analysis/gauge_RDS_files/'

dir.create(output_basedir, showWarnings=FALSE, recursive=TRUE)

# Copy over files beginning with 'gauge*'
all_gauge_files = Sys.glob('OUTPUTS/*/*/gauge*')
# Copy over the multidomain log for 'image 1' [i.e. mpi-rank = 0]. All individual log-files
# include global energy balance and mass balance information so we don't need them all.
all_md_files = paste0(dirname(all_gauge_files), '/multidomain_log_image_00000000000000000001.log')

for(i in 1:length(all_gauge_files)){
    gauge_file = all_gauge_files[i]
    output_dir = paste0(output_basedir, dirname(gauge_file))
    dir.create(output_dir, showWarnings=FALSE, recursive=TRUE)
    file.copy(gauge_file, paste0(output_dir, '/', basename(gauge_file)), overwrite=TRUE)
    file.copy(all_md_files[i], paste0(output_dir, '/', basename(all_md_files[i])), overwrite=TRUE)

    # Assume we copy a matching gauge_*.RDS file and a gauge*.pdf file, as well
    # as a bunch of tifs. Here we only copy the tifs with pdf files, to avoid double copy.
    if(endsWith(gauge_file, 'pdf')){
        all_tifs = Sys.glob(paste0(dirname(gauge_file), '/*.tif'))
        for(j in 1:length(all_tifs)){
            file.copy(all_tifs[j], 
            paste0(output_dir, '/', basename(all_tifs[j])), 
                overwrite=TRUE)
        }
    }
}

