#
# Make a clean directory structure for the tifs generated by 
#    run_compute_exceedance_rates_for_threshold_depth_logic_tree_mean_newParallelPartition.sh
# AND 
#    all the *.sh scripts generated by `make_exceedance_rate_jobs.R` (epistemic uncertainty calcs over multiple nodes)
#

runname='ptha18-BunburyBusseltonRevised-sealevel60cm'

# Move logic-tree-mean hazard & variance rasters to a clean location
mkdir -p $runname/highres_with_variance
mv $runname-random* $runname/highres_with_variance    

# Move epistemic uncertainty rasters to a clean location
mkdir -p $runname/highres_epistemic_uncertainty  
# 16th percentile
mkdir -p $runname/highres_epistemic_uncertainty/16pc  
mv $runname-depth_exrate_0.001_0.16_outerrisesunda $runname/highres_epistemic_uncertainty/16pc/
mv $runname-depth_exrate_0.001_0.16_sunda2 $runname/highres_epistemic_uncertainty/16pc/
# 84th percentile
mkdir -p $runname/highres_epistemic_uncertainty/84pc  
mv $runname-depth_exrate_0.001_0.84_outerrisesunda $runname/highres_epistemic_uncertainty/84pc/
mv $runname-depth_exrate_0.001_0.84_sunda2 $runname/highres_epistemic_uncertainty/84pc/
