module load gdal

# dir=sea_level_1.459/highres_depth_with_variance/sea_level_1.459-depth-LogicTreeMean-sum_of_source_zones

# gdalbuildvrt -resolution highest $dir/exceedance_rate_with_threshold_0.001.vrt $dir/summed_HS_domain*depth_as_max_stage_minus_elevation0_domain__exceedance_rate_with_threshold_0.001.tif
# gdalbuildvrt -resolution highest $dir/variance_of__exceedance_rate_with_threshold_0.001.vrt $dir/summed_HS_domain*depth_as_max_stage_minus_elevation0_domain__variance_of__exceedance_rate_with_threshold_0.001.tif
# gdalbuildvrt -resolution highest $dir/Monte_Carlo_Upper_CI__exceedance_rate_with_threshold_0.001.vrt $dir/summed_HS_domain*depth_as_max_stage_minus_elevation0_domain__Monte_Carlo_Upper_CI__exceedance_rate_with_threshold_0.001.tif

# for comparison rasters
dir=sea_level_1.459/highres_depth_with_variance/sea_level_1.459-depth-LogicTreeMean-sum_of_source_zones-comparison

# gdalbuildvrt -resolution highest $dir/abs_diff_exceedance_rate_with_threshold_0.001.vrt $dir/absolute_diff_summed_HS_domain*depth_as_max_stage_minus_elevation0_domain__exceedance_rate_with_threshold_0.001.tif
# gdalbuildvrt -resolution highest $dir/abs_diff_variance_of__exceedance_rate_with_threshold_0.001.vrt $dir/absolute_diff_summed_HS_domain*depth_as_max_stage_minus_elevation0_domain__variance_of__exceedance_rate_with_threshold_0.001.tif
# gdalbuildvrt -resolution highest $dir/abs_diff_Monte_Carlo_Upper_CI__exceedance_rate_with_threshold_0.001.vrt $dir/absolute_diff_summed_HS_domain*depth_as_max_stage_minus_elevation0_domain__Monte_Carlo_Upper_CI__exceedance_rate_with_threshold_0.001.tif

# gdalbuildvrt -resolution highest $dir/rel_diff_exceedance_rate_with_threshold_0.001.vrt $dir/relative_diff_summed_HS_domain*depth_as_max_stage_minus_elevation0_domain__exceedance_rate_with_threshold_0.001.tif
# gdalbuildvrt -resolution highest $dir/rel_diff_variance_of__exceedance_rate_with_threshold_0.001.vrt $dir/relative_diff_summed_HS_domain*depth_as_max_stage_minus_elevation0_domain__variance_of__exceedance_rate_with_threshold_0.001.tif
# gdalbuildvrt -resolution highest $dir/rel_diff_Monte_Carlo_Upper_CI__exceedance_rate_with_threshold_0.001.vrt $dir/relative_diff_summed_HS_domain*depth_as_max_stage_minus_elevation0_domain__Monte_Carlo_Upper_CI__exceedance_rate_with_threshold_0.001.tif

gdalbuildvrt -resolution highest $dir/diff_exceedance_rate_with_threshold_0.01.vrt $dir/diff_summed_HS_domain*depth_as_max_stage_minus_elevation0_domain__exceedance_rate_with_threshold_0.001.tif
gdalbuildvrt -resolution highest $dir/diff_variance_of__exceedance_rate_with_threshold_0.01.vrt $dir/diff_summed_HS_domain*depth_as_max_stage_minus_elevation0_domain__variance_of__exceedance_rate_with_threshold_0.001.tif
gdalbuildvrt -resolution highest $dir/diff_Monte_Carlo_Upper_CI__exceedance_rate_with_threshold_0.01.vrt $dir/diff_summed_HS_domain*depth_as_max_stage_minus_elevation0_domain__Monte_Carlo_Upper_CI__exceedance_rate_with_threshold_0.001.tif
