#!/bin/bash
#PBS -P w85
#PBS -q normal
#PBS -l walltime=24:00:00
#PBS -lmem=64GB
#PBS -lncpus=16
#PBS -l wd

# Source key R modules -- not that you will need the right packages installed
# as well (see comments in the script that is sourced)
source R_modules.sh
Rscript compute_rates_all_sources.R
Rscript compute_station_hazard_curves.R
Rscript plot_hazard_curves.R
Rscript integrated_rate_given_stage.R
